// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxokqkrepwgvqcquzwiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4b2txa3JlcHdndnFjcXV6d2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMDM1MDEsImV4cCI6MjA4NDY3OTUwMX0.ar1IY8mIEAdtMjjxoKfeqloiIQqUZynBrZG3-yCMpJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
