// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suoffsrethbczunoanmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1b2Zmc3JldGhiY3p1bm9hbm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjE2NzYsImV4cCI6MjA3MDAzNzY3Nn0.W51_QeMg5KiDRYRP0xpFydxkL1Qw74YMFESlb4uWomM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});